// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppAlert: typeof import('./src/components/AppAlert.vue')['default']
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    AppCatalogButton: typeof import('./src/components/AppCatalogButton.vue')['default']
    AppNavbar: typeof import('./src/components/AppNavbar/index.vue')['default']
    AppSearch: typeof import('./src/components/AppSearch.vue')['default']
    AppVideo: typeof import('./src/components/AppVideo.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LayoutContainer: typeof import('./src/components/LayoutContainer/index.vue')['default']
    ListOfCards: typeof import('./src/components/ListOfCards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheDescription: typeof import('./src/components/LayoutContainer/TheDescription.vue')['default']
    TheLoginForm: typeof import('./src/components/LayoutContainer/TheLoginForm.vue')['default']
    TheRegistrationForm: typeof import('./src/components/LayoutContainer/TheRegistrationForm.vue')['default']
    WebServicesIcons: typeof import('./src/components/LayoutContainer/WebServicesIcons/index.vue')['default']
  }
}
