// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AppAlert: typeof import("./src/components/AppAlert.vue")["default"];
    AppBackButton: typeof import("./src/components/AppBackButton.vue")["default"];
    AppCatalogButton: typeof import("./src/components/AppCatalogButton.vue")["default"];
    AppFooter: typeof import("./src/components/AppFooter.vue")["default"];
    AppListOfModules: typeof import("./src/components/AppListOfModules.vue")["default"];
    AppListOfThemes: typeof import("./src/components/AppListOfThemes.vue")["default"];
    AppModule: typeof import("./src/components/AppModule.vue")["default"];
    AppNavbar: typeof import("./src/components/AppNavbar/index.vue")["default"];
    AppProgress: typeof import("./src/components/AppProgress.vue")["default"];
    AppRing: typeof import("./src/components/AppRing.vue")["default"];
    AppSearch: typeof import("./src/components/AppSearch.vue")["default"];
    AppTabs: typeof import("./src/components/AppTabs.vue")["default"];
    AppTestAnswer: typeof import("./src/components/AppTestBlock/AppTestAnswer.vue")["default"];
    AppTestAnswerBlock: typeof import("./src/components/AppTestBlock/AppTestAnswerBlock.vue")["default"];
    AppTestBlock: typeof import("./src/components/AppTestBlock/index.vue")["default"];
    AppTestContent: typeof import("./src/components/AppTestBlock/AppTestContent.vue")["default"];
    AppTestDescription: typeof import("./src/components/AppTestBlock/AppTestDescription.vue")["default"];
    AppTestLoader: typeof import("./src/components/AppTestBlock/AppTestLoader.vue")["default"];
    AppTestOptions: typeof import("./src/components/AppTestBlock/AppTestOptions.vue")["default"];
    AppTestPassingButton: typeof import("./src/components/AppTestBlock/AppTestPassingButton.vue")["default"];
    AppTestPassingIndicator: typeof import("./src/components/AppTestBlock/AppTestPassingIndicator.vue")["default"];
    AppTestPercentAnswers: typeof import("./src/components/AppTestBlock/AppTestPercentAnswers.vue")["default"];
    AppTestQuestion: typeof import("./src/components/AppTestBlock/AppTestQuestion.vue")["default"];
    AppTestRestart: typeof import("./src/components/AppTestBlock/AppTestRestart.vue")["default"];
    AppTestResultButton: typeof import("./src/components/AppTestBlock/AppTestResultButton.vue")["default"];
    AppTestResultCoins: typeof import("./src/components/AppTestBlock/AppTestResultCoins.vue")["default"];
    AppTheme: typeof import("./src/components/AppTheme.vue")["default"];
    AppThemeHeader: typeof import("./src/components/AppThemeHeader.vue")["default"];
    AppTitle: typeof import("./src/components/AppTitle.vue")["default"];
    AppTitleLine: typeof import("./src/components/AppTitleLine.vue")["default"];
    AppVideo: typeof import("./src/components/AppVideo.vue")["default"];
    ElAlert: typeof import("element-plus/es")["ElAlert"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElProgress: typeof import("element-plus/es")["ElProgress"];
    ElTabPane: typeof import("element-plus/es")["ElTabPane"];
    ElTabs: typeof import("element-plus/es")["ElTabs"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    LayoutContainer: typeof import("./src/components/LayoutContainer/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    TheDescription: typeof import("./src/components/LayoutContainer/TheDescription.vue")["default"];
    TheLoginForm: typeof import("./src/components/LayoutContainer/TheLoginForm.vue")["default"];
    TheRegistrationForm: typeof import("./src/components/LayoutContainer/TheRegistrationForm.vue")["default"];
    WebServicesIcons: typeof import("./src/components/LayoutContainer/WebServicesIcons/index.vue")["default"];
  }
}
