const BASE_URL = "http://localhost:3000";
const BASE_URL_MODULES = `${BASE_URL}/modules`;
const BASE_URL_VIDEOS = `${BASE_URL}/videos`;
const BASE_URL_ASSETS = `${BASE_URL}/assets`;
const BASE_URL_MODULES_UPLOAD = `${BASE_URL_MODULES}/upload`;
const BASE_URL_ASSETS_MODULES_CARDCOVER = `${BASE_URL_ASSETS}/modules/cardCover`;
const BASE_URL_VIDEOS_UPLOAD_POSTER = `${BASE_URL_VIDEOS}/upload-video-poster`;
const BASE_URL_VIDEOS_UPLOAD_VIDEO_FILE = `${BASE_URL_VIDEOS}/upload-video-file`;
const BASE_URL_ASSETS_VIDEOS_POSTER = `${BASE_URL_ASSETS}/videos/poster`;
const BASE_URL_ASSETS_VIDEOS_VIDEO_FILE = `${BASE_URL_ASSETS}/videos/video-file`;
const BASE_URL_VIDEOS_UPDATE_VIDEO_STATE = `${BASE_URL_VIDEOS}/update-video-state`;

export {
  BASE_URL,
  BASE_URL_MODULES,
  BASE_URL_VIDEOS,
  BASE_URL_ASSETS,
  BASE_URL_MODULES_UPLOAD,
  BASE_URL_ASSETS_MODULES_CARDCOVER,
  BASE_URL_VIDEOS_UPLOAD_POSTER,
  BASE_URL_VIDEOS_UPLOAD_VIDEO_FILE,
  BASE_URL_ASSETS_VIDEOS_POSTER,
  BASE_URL_ASSETS_VIDEOS_VIDEO_FILE,
  BASE_URL_VIDEOS_UPDATE_VIDEO_STATE,
};
