// Mock object represent database data
import { EEntityState, EEntityType } from "share/types/enums";
import type { IVideo } from "share/types/interfaces";
import type { TElemsList } from "share/types/types";

/**
 * VIDEOS
 */
const videos: TElemsList<number, IVideo> | undefined = new Map();
// id_module 1
videos.set(1, [
  {
    id: 1,
    type: EEntityType.Videos,
    filename: "/src/assets/video/srcs/1.mp4",
    poster: "/src/assets/video/posters/1.png",
    videoType: "",
    state: EEntityState.Active,
    title: "Введение в курс",
    authors: [
      {
        id: 1,
        type: EEntityType.TabsAuthors,
        surname: "Сазонов",
        name: "Борис",
        patronymic: "",
        regalia:
          'генеральный директор компании "Дом Здоровья Уфа": 8 магазинов в 4 городах РФ; директор по развитию бизнес-академии "Умный бизнес"; победитель управленческого конкурса "Лидеры Башкортостана"; председатель Уфимского отделения БРО ОПОРА РОССИИ',
      },
    ],
    description: "Введение в бизнес",
  },
  {
    id: 2,
    type: EEntityType.Videos,
    filename: "/src/assets/video/srcs/2.mp4",
    poster: "/src/assets/video/posters/2.png",
    videoType: "",
    state: EEntityState.Default,
    title: `Урок 1 "Бизнеc как профессия"`,
    authors: [
      {
        id: 1,
        type: EEntityType.TabsAuthors,
        surname: "Сазонов",
        name: "Борис",
        patronymic: "",
        regalia:
          'генеральный директор компании "Дом Здоровья Уфа": 8 магазинов в 4 городах РФ; директор по развитию бизнес-академии "Умный бизнес"; победитель управленческого конкурса "Лидеры Башкортостана"; председатель Уфимского отделения БРО ОПОРА РОССИИ',
      },
    ],
    description:
      'Кто такой современный предприниматель? Где их обучают и чему предстоит научиться; "+" и "-" предпринимательства; типичные ошибки начинающих предпринимателей; ожидания и реальность',
  },
  {
    id: 3,
    type: EEntityType.Videos,
    filename: "/src/assets/video/srcs/3.mp4",
    poster: "/src/assets/video/posters/3.png",
    videoType: "",
    state: EEntityState.Default,
    title: `Урок 2 "С чего начать новый бизнес?"`,
    authors: [
      {
        id: 1,
        type: EEntityType.TabsAuthors,
        surname: "Сазонов",
        name: "Борис",
        patronymic: "",
        regalia:
          'генеральный директор компании "Дом Здоровья Уфа": 8 магазинов в 4 городах РФ; директор по развитию бизнес-академии "Умный бизнес"; победитель управленческого конкурса "Лидеры Башкортостана"; председатель Уфимского отделения БРО ОПОРА РОССИИ',
      },
    ],
    description: "С чего начать новый бизнес, если есть идея?",
  },
  {
    id: 4,
    type: EEntityType.Videos,
    filename: "/src/assets/video/srcs/4.mp4",
    poster: "/src/assets/video/posters/4.png",
    videoType: "",
    state: EEntityState.Default,
    title: `Урок 3 "Бизнес-модель"`,
    authors: [
      {
        id: 1,
        type: EEntityType.TabsAuthors,
        surname: "Сазонов",
        name: "Борис",
        patronymic: "",
        regalia:
          'генеральный директор компании "Дом Здоровья Уфа": 8 магазинов в 4 городах РФ; директор по развитию бизнес-академии "Умный бизнес"; победитель управленческого конкурса "Лидеры Башкортостана"; председатель Уфимского отделения БРО ОПОРА РОССИИ',
      },
    ],
    description: "Бизнес-модель",
  },
  {
    id: 5,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 5",
    authors: [
      {
        id: 1,
        type: EEntityType.TabsAuthors,
        surname: "Иванов",
        name: "Игнат",
        patronymic: "Ираклиевич",
        regalia: "",
      },
      {
        id: 2,
        type: EEntityType.TabsAuthors,
        surname: "Калмыков",
        name: "Камиль",
        patronymic: "Камалетдинович",
        regalia: "",
      },
      {
        id: 3,
        type: EEntityType.TabsAuthors,
        surname: "Бахча",
        name: "Бергамот",
        patronymic: "Балыкович",
        regalia: "",
      },
      {
        id: 4,
        type: EEntityType.TabsAuthors,
        surname: "Савушкин",
        name: "Савелий",
        patronymic: "Севастьянович",
        regalia: "к.ф.-м.н.",
      },
      {
        id: 5,
        type: EEntityType.TabsAuthors,
        surname: "Гагаладзе",
        name: "Гар",
        patronymic: "Гора оглы",
        regalia: "д.ф.н.",
      },
    ],
    description: "",
  },
  {
    id: 6,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 6",
    authors: [],
    description: "",
  },
  {
    id: 8,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 8",
    authors: [],
    description: "",
  },
  {
    id: 9,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 9",
    authors: [],
    description: "",
  },
  {
    id: 10,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 10",
    authors: [],
    description: "",
  },
  {
    id: 11,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 11",
    authors: [],
    description: "",
  },
  {
    id: 12,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 12",
    authors: [],
    description: "",
  },
  {
    id: 13,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 13",
    authors: [],
    description: "",
  },
  {
    id: 15,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 15",
    authors: [],
    description: "",
  },
  {
    id: 16,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 16",
    authors: [],
    description: "",
  },
  {
    id: 17,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 17",
    authors: [],
    description: "",
  },
  {
    id: 18,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 18",
    authors: [],
    description: "",
  },
  {
    id: 19,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 19",
    authors: [],
    description: "",
  },
  {
    id: 20,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 20",
    authors: [],
    description: "",
  },
  {
    id: 21,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 21",
    authors: [],
    description: "",
  },
  {
    id: 22,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 22",
    authors: [],
    description: "",
  },
  {
    id: 23,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 23",
    authors: [],
    description: "",
  },
  {
    id: 24,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 24",
    authors: [],
    description: "",
  },
  {
    id: 25,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 25",
    authors: [],
    description: "",
  },
  {
    id: 26,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 26",
    authors: [],
    description: "",
  },
  {
    id: 27,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 27",
    authors: [],
    description: "",
  },
]);

// id_module 2
videos.set(2, [
  {
    id: 29,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Active,
    title: "video title module 2 videos id 29",
    authors: [],
    description: "",
  },
  {
    id: 30,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 30",
    authors: [],
    description: "",
  },
  {
    id: 31,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 31",
    authors: [],
    description: "",
  },
  {
    id: 32,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 32",
    authors: [],
    description: "",
  },
  {
    id: 33,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 33",
    authors: [],
    description: "",
  },
  {
    id: 34,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 34",
    authors: [],
    description: "",
  },
  {
    id: 35,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 35",
    authors: [],
    description: "",
  },
  {
    id: 36,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 36",
    authors: [],
    description: "",
  },
  {
    id: 37,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 37",
    authors: [],
    description: "",
  },
  {
    id: 38,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 38",
    authors: [],
    description: "",
  },
]);

// id_module 3
videos.set(3, [
  {
    id: 40,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Active,
    title: "video title module 3 videos theme 1 id 40",
    authors: [],
    description: "",
  },
  {
    id: 41,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos theme 2 id 41",
    authors: [],
    description: "",
  },
  {
    id: 42,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos theme 3 id 42",
    authors: [],
    description: "",
  },
  {
    id: 43,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos id 43",
    authors: [],
    description: "",
  },
  {
    id: 44,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos id 44",
    authors: [],
    description: "",
  },
  {
    id: 45,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos id 45",
    authors: [],
    description: "",
  },
  {
    id: 46,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos id 46",
    authors: [],
    description: "",
  },
  {
    id: 47,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos id 47",
    authors: [],
    description: "",
  },
  {
    id: 48,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos id 48",
    authors: [],
    description: "",
  },
  {
    id: 49,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos id 49",
    authors: [],
    description: "",
  },
]);

// id_module 4
videos.set(4, [
  {
    id: 51,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 51",
    authors: [],
    description: "",
  },
  {
    id: 52,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Active,
    title: "video title module 4 videos id 52",
    authors: [],
    description: "",
  },
  {
    id: 53,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 53",
    authors: [],
    description: "",
  },
  {
    id: 54,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 54",
    authors: [],
    description: "",
  },
  {
    id: 55,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 55",
    authors: [],
    description: "",
  },
  {
    id: 56,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 56",
    authors: [],
    description: "",
  },
  {
    id: 57,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 57",
    authors: [],
    description: "",
  },
  {
    id: 58,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 58",
    authors: [],
    description: "",
  },
  {
    id: 59,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 59",
    authors: [],
    description: "",
  },
  {
    id: 60,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 60",
    authors: [],
    description: "",
  },
  {
    id: 61,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 61",
    authors: [],
    description: "",
  },
  {
    id: 62,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 62",
    authors: [],
    description: "",
  },
  {
    id: 63,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 63",
    authors: [],
    description: "",
  },
  {
    id: 64,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 64",
    authors: [],
    description: "",
  },
]);

// id_module 5
videos.set(5, [
  {
    id: 66,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Active,
    title: "video title module 5 videos id 66",
    authors: [],
    description: "",
  },
  {
    id: 67,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 5 videos id 67",
    authors: [],
    description: "",
  },
  {
    id: 68,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 5 videos id 68",
    authors: [],
    description: "",
  },
  {
    id: 69,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 5 videos id 69",
    authors: [],
    description: "",
  },
  {
    id: 70,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 5 videos id 70",
    authors: [],
    description: "",
  },
]);

// id_module 6
videos.set(6, [
  {
    id: 72,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 6 videos id 72",
    authors: [],
    description: "",
  },
  {
    id: 73,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 6 videos id 73",
    authors: [],
    description: "",
  },
  {
    id: 74,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 6 videos id 74",
    authors: [],
    description: "",
  },
  {
    id: 75,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Active,
    title: "video title module 6 videos id 75",
    authors: [],
    description: "",
  },
  {
    id: 76,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 6 videos id 76",
    authors: [],
    description: "",
  },
  {
    id: 77,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 6 videos id 77",
    authors: [],
    description: "",
  },
  {
    id: 78,
    type: EEntityType.Videos,
    filename: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 6 videos id 78",
    authors: [],
    description: "",
  },
]);

export { videos };
