// Mock object represent database data
import { EEntityState, EEntityType, EGuessed } from "@/types/enums";
import type {
  IModule,
  ITheme,
  IVideo,
  ITest,
  ITestContent,
  IEntranceTestContent,
  IEntranceTest,
} from "@/types/interfaces";
import type { TElemsList } from "@/types/types";

/**
 * MODULES
 */
const modules: IModule[] | undefined = [];
modules.push(
  {
    id: 1,
    type: EEntityType.Modules,
    src: "https://catherineasquithgallery.com/uploads/posts/2021-03/1614630830_77-p-fon-knigi-dlya-fotoshopa-110.jpg",
    alt: "Модуль 1",
    header: "Основы предпринимательства",
    title: "Модуль 1",
    duration: "2 часа",
    footer: "Изучить модуль",
    state: EEntityState.Active,
  },
  {
    id: 2,
    type: EEntityType.Modules,
    src: "https://catherineasquithgallery.com/uploads/posts/2021-03/1614630830_77-p-fon-knigi-dlya-fotoshopa-110.jpg",
    alt: "Модуль 2",
    header: "Грантовое проектирование",
    title: "Модуль 2",
    duration: "1 час 20 минут",
    footer: "Изучить модуль",
    state: EEntityState.Default,
  },
  {
    id: 3,
    type: EEntityType.Modules,
    src: "https://catherineasquithgallery.com/uploads/posts/2021-03/1614630830_77-p-fon-knigi-dlya-fotoshopa-110.jpg",
    alt: "Модуль 3",
    header: "Технологическое предпринимательство",
    title: "Модуль 3",
    duration: "2 часа 15 минут",
    footer: "Изучить модуль",
    state: EEntityState.Default,
  },
  {
    id: 4,
    type: EEntityType.Modules,
    src: "https://catherineasquithgallery.com/uploads/posts/2021-03/1614630830_77-p-fon-knigi-dlya-fotoshopa-110.jpg",
    alt: "Модуль 4",
    header: "Массовое предпринимательство",
    title: "Модуль 4",
    duration: "43 минуты",
    footer: "Изучить модуль",
    state: EEntityState.Default,
  },
  {
    id: 5,
    type: EEntityType.Modules,
    src: "https://catherineasquithgallery.com/uploads/posts/2021-03/1614630830_77-p-fon-knigi-dlya-fotoshopa-110.jpg",
    alt: "Модуль 5",
    header: "Креативные индустрии",
    title: "Модуль 5",
    duration: "37 минут",
    footer: "Изучить модуль",
    state: EEntityState.Default,
  },
  {
    id: 6,
    type: EEntityType.Modules,
    src: "https://catherineasquithgallery.com/uploads/posts/2021-03/1614630830_77-p-fon-knigi-dlya-fotoshopa-110.jpg",
    alt: "Модуль 6",
    header: "Социальное предпринимательство",
    title: "Модуль 6",
    duration: "2 часа 7 минут",
    footer: "Изучить модуль",
    state: EEntityState.Default,
  },
  {
    id: 7,
    type: EEntityType.Modules,
    src: "https://catherineasquithgallery.com/uploads/posts/2021-03/1614630830_77-p-fon-knigi-dlya-fotoshopa-110.jpg",
    alt: "Модуль 7",
    header: "Итоговое тестирование",
    title: "Модуль 7",
    duration: "30 минут",
    footer: "Изучить модуль",
    state: EEntityState.Default,
  }
);

/**
 * THEMES
 */
const themes: TElemsList<number, ITheme> | undefined = new Map();
// id_module 1
themes.set(1, [
  {
    id: 1,
    type: EEntityType.Topics,
    state: EEntityState.Active,
    title: "topic 1 theme 1",
  },
  {
    id: 2,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "two",
  },
  {
    id: 3,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "sdfg",
  },
  {
    id: 4,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "fghjfhj",
  },
  {
    id: 5,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "zxcv",
  },
  {
    id: 6,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "345345",
  },
  {
    id: 7,
    type: EEntityType.Tests,
    state: EEntityState.Default,
    title: "Тестирование 1",
  },
  {
    id: 8,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "asdf",
  },
  {
    id: 9,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "234",
  },
  {
    id: 10,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "десять",
  },
  {
    id: 11,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "Интересная тема",
  },
  {
    id: 12,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "zxcv",
  },
  {
    id: 13,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "345345",
  },
  {
    id: 14,
    type: EEntityType.Tests,
    state: EEntityState.Default,
    title: "Тестирование 2",
  },
  {
    id: 15,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "asdf",
  },
  {
    id: 16,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "234",
  },
  {
    id: 17,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "десять",
  },
  {
    id: 18,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "одиннадцать 1",
  },
  {
    id: 19,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "1",
  },
  {
    id: 20,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "11",
  },
  {
    id: 21,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "111",
  },
  {
    id: 22,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "1e4 1",
  },
  {
    id: 23,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "1e5 1",
  },
  {
    id: 24,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "1е6 1",
  },
  {
    id: 25,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "1e7 1",
  },
  {
    id: 26,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "1e8 1",
  },
  {
    id: 27,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "1e9 1",
  },
  {
    id: 28,
    type: EEntityType.Tests,
    state: EEntityState.Default,
    title: "Тестирование 3",
  },
]);

// id_module 2
themes.set(2, [
  {
    id: 29,
    type: EEntityType.Topics,
    state: EEntityState.Active,
    title: "topic 2 theme 1",
  },
  {
    id: 30,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "two",
  },
  {
    id: 31,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "sdfg",
  },
  {
    id: 32,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "fghjfhj",
  },
  {
    id: 33,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "zxcv",
  },
  {
    id: 34,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "345345",
  },
  {
    id: 35,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "7",
  },
  {
    id: 36,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "asdf",
  },
  {
    id: 37,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "234",
  },
  {
    id: 38,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "десять",
  },
  {
    id: 39,
    type: EEntityType.Tests,
    state: EEntityState.Default,
    title: "Тестирование 2",
  },
]);

// id_module 3
themes.set(3, [
  {
    id: 40,
    type: EEntityType.Topics,
    state: EEntityState.Active,
    title: "topic 3 theme 1",
  },
  {
    id: 41,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "two",
  },
  {
    id: 42,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "sdfg",
  },
  {
    id: 43,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "fghjfhj",
  },
  {
    id: 44,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "zxcv",
  },
  {
    id: 45,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "345345",
  },
  {
    id: 46,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "7",
  },
  {
    id: 47,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "asdf",
  },
  {
    id: 48,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "234",
  },
  {
    id: 49,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "десять",
  },
  {
    id: 50,
    type: EEntityType.Tests,
    state: EEntityState.Default,
    title: "Тестирование 3",
  },
]);

// id_module 4
themes.set(4, [
  {
    id: 51,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "topic 4 theme 1",
  },
  {
    id: 52,
    type: EEntityType.Topics,
    state: EEntityState.Active,
    title: "topic 4 theme 2",
  },
  {
    id: 53,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "sdfg",
  },
  {
    id: 54,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "fghjfhj",
  },
  {
    id: 55,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "zxcv",
  },
  {
    id: 56,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "345345",
  },
  {
    id: 57,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "7",
  },
  {
    id: 58,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "asdf",
  },
  {
    id: 59,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "234",
  },
  {
    id: 60,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "десять",
  },
  {
    id: 61,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "что-то ещё",
  },
  {
    id: 62,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "asdf",
  },
  {
    id: 63,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "234",
  },
  {
    id: 64,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "десять",
  },
  {
    id: 65,
    type: EEntityType.Tests,
    state: EEntityState.Default,
    title: "Тестирование 4",
  },
]);

// id_module 5
themes.set(5, [
  {
    id: 66,
    type: EEntityType.Topics,
    state: EEntityState.Active,
    title: "topic 5 theme 1",
  },
  {
    id: 67,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "two",
  },
  {
    id: 68,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "sdfg",
  },
  {
    id: 69,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "fghjfhj",
  },
  {
    id: 70,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "zxcv",
  },
  {
    id: 71,
    type: EEntityType.Tests,
    state: EEntityState.Default,
    title: "Тестирование 5",
  },
]);

// id_module 6
themes.set(6, [
  {
    id: 72,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "topic 6 theme 1",
  },
  {
    id: 73,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "two",
  },
  {
    id: 74,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "345345",
  },
  {
    id: 75,
    type: EEntityType.Topics,
    state: EEntityState.Active,
    title: "topic 6 theme 4",
  },
  {
    id: 76,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "asdf",
  },
  {
    id: 77,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "234",
  },
  {
    id: 78,
    type: EEntityType.Topics,
    state: EEntityState.Default,
    title: "десять",
  },
  {
    id: 79,
    type: EEntityType.Tests,
    state: EEntityState.Default,
    title: "Тестирование 6",
  },
]);

// id_module 7
themes.set(7, [
  {
    id: 80,
    type: EEntityType.Tests,
    state: EEntityState.Active,
    title: "test 7 theme 1",
  },
]);

/**
 * VIDEOS
 */
const videos: TElemsList<number, IVideo> | undefined = new Map();
// id_module 1
videos.set(1, [
  {
    id: 1,
    type: EEntityType.Videos,
    src: "../assets/video/srcs/1.mp4",
    poster: "../assets/video/posters/1.png",
    videoType: "",
    state: EEntityState.Active,
    title: "Приветствие",
    authors: [
      {
        id: 1,
        surname: "Сазонов",
        name: "Борис",
        patronymic: "Отчество",
        regalia:
          "член Общественной палаты Башкортостана, председатель Уфимского отделения БРО Опора России",
      },
    ],
    description: "Введение в бизнес",
  },
  {
    id: 2,
    type: EEntityType.Videos,
    src: "../assets/video/srcs/2.mp4",
    poster: "../assets/video/posters/2.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 2",
    authors: [
      {
        id: 1,
        surname: "Сазонов",
        name: "Борис",
        patronymic: "",
        regalia:
          "член Общественной палаты Башкортостана, председатель Уфимского отделения БРО Опора России",
      },
    ],
    description: "Кто такой современный предприниматель?",
  },
  {
    id: 3,
    type: EEntityType.Videos,
    src: "../assets/video/srcs/3.mp4",
    poster: "../assets/video/posters/3.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 3",
    authors: [
      {
        id: 1,
        surname: "Сазонов",
        name: "Борис",
        patronymic: "",
        regalia:
          "член Общественной палаты Башкортостана, председатель Уфимского отделения БРО Опора России",
      },
    ],
    description: "С чего начать новый бизнес, если есть идея?",
  },
  {
    id: 4,
    type: EEntityType.Videos,
    src: "../assets/video/srcs/4.mp4",
    poster: "../assets/video/posters/4.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 4",
    authors: [
      {
        id: 1,
        surname: "Сазонов",
        name: "Борис",
        patronymic: "",
        regalia:
          "член Общественной палаты Башкортостана, председатель Уфимского отделения БРО Опора России",
      },
    ],
    description: "Бизнес-модель",
  },
  {
    id: 5,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 5",
    authors: [
      {
        id: 1,
        surname: "Иванов",
        name: "Игнат",
        patronymic: "Ираклиевич",
        regalia: "",
      },
      {
        id: 2,
        surname: "Калмыков",
        name: "Камиль",
        patronymic: "Камалетдинович",
        regalia: "",
      },
      {
        id: 3,
        surname: "Бахча",
        name: "Бергамот",
        patronymic: "Балыкович",
        regalia: "",
      },
      {
        id: 4,
        surname: "Савушкин",
        name: "Савелий",
        patronymic: "Севастьянович",
        regalia: "к.ф.-м.н.",
      },
      {
        id: 5,
        surname: "Гагаладзе",
        name: "Гар",
        patronymic: "Гора оглы",
        regalia: "д.ф.н.",
      },
    ],
    description: "",
  },
  {
    id: 6,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 6",
    authors: [],
    description: "",
  },
  {
    id: 8,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 8",
    authors: [],
    description: "",
  },
  {
    id: 9,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 9",
    authors: [],
    description: "",
  },
  {
    id: 10,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 10",
    authors: [],
    description: "",
  },
  {
    id: 11,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 11",
    authors: [],
    description: "",
  },
  {
    id: 12,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 12",
    authors: [],
    description: "",
  },
  {
    id: 13,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 13",
    authors: [],
    description: "",
  },
  {
    id: 15,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 15",
    authors: [],
    description: "",
  },
  {
    id: 16,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 16",
    authors: [],
    description: "",
  },
  {
    id: 17,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 17",
    authors: [],
    description: "",
  },
  {
    id: 18,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 18",
    authors: [],
    description: "",
  },
  {
    id: 19,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 19",
    authors: [],
    description: "",
  },
  {
    id: 20,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 20",
    authors: [],
    description: "",
  },
  {
    id: 21,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 21",
    authors: [],
    description: "",
  },
  {
    id: 22,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 22",
    authors: [],
    description: "",
  },
  {
    id: 23,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 23",
    authors: [],
    description: "",
  },
  {
    id: 24,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 24",
    authors: [],
    description: "",
  },
  {
    id: 25,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 25",
    authors: [],
    description: "",
  },
  {
    id: 26,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 26",
    authors: [],
    description: "",
  },
  {
    id: 27,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 1 videos id 27",
    authors: [],
    description: "",
  },
]);

// id_module 2
videos.set(2, [
  {
    id: 29,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Active,
    title: "video title module 2 videos id 29",
    authors: [],
    description: "",
  },
  {
    id: 30,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 30",
    authors: [],
    description: "",
  },
  {
    id: 31,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 31",
    authors: [],
    description: "",
  },
  {
    id: 32,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 32",
    authors: [],
    description: "",
  },
  {
    id: 33,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 33",
    authors: [],
    description: "",
  },
  {
    id: 34,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 34",
    authors: [],
    description: "",
  },
  {
    id: 35,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 35",
    authors: [],
    description: "",
  },
  {
    id: 36,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 36",
    authors: [],
    description: "",
  },
  {
    id: 37,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 37",
    authors: [],
    description: "",
  },
  {
    id: 38,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 2 videos id 38",
    authors: [],
    description: "",
  },
]);

// id_module 3
videos.set(3, [
  {
    id: 40,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Active,
    title: "video title module 3 videos theme 1 id 40",
    authors: [],
    description: "",
  },
  {
    id: 41,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos theme 2 id 41",
    authors: [],
    description: "",
  },
  {
    id: 42,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos theme 3 id 42",
    authors: [],
    description: "",
  },
  {
    id: 43,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos id 43",
    authors: [],
    description: "",
  },
  {
    id: 44,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos id 44",
    authors: [],
    description: "",
  },
  {
    id: 45,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos id 45",
    authors: [],
    description: "",
  },
  {
    id: 46,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos id 46",
    authors: [],
    description: "",
  },
  {
    id: 47,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos id 47",
    authors: [],
    description: "",
  },
  {
    id: 48,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos id 48",
    authors: [],
    description: "",
  },
  {
    id: 49,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 3 videos id 49",
    authors: [],
    description: "",
  },
]);

// id_module 4
videos.set(4, [
  {
    id: 51,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 51",
    authors: [],
    description: "",
  },
  {
    id: 52,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Active,
    title: "video title module 4 videos id 52",
    authors: [],
    description: "",
  },
  {
    id: 53,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 53",
    authors: [],
    description: "",
  },
  {
    id: 54,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 54",
    authors: [],
    description: "",
  },
  {
    id: 55,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 55",
    authors: [],
    description: "",
  },
  {
    id: 56,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 56",
    authors: [],
    description: "",
  },
  {
    id: 57,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 57",
    authors: [],
    description: "",
  },
  {
    id: 58,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 58",
    authors: [],
    description: "",
  },
  {
    id: 59,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 59",
    authors: [],
    description: "",
  },
  {
    id: 60,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 60",
    authors: [],
    description: "",
  },
  {
    id: 61,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 61",
    authors: [],
    description: "",
  },
  {
    id: 62,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 62",
    authors: [],
    description: "",
  },
  {
    id: 63,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 63",
    authors: [],
    description: "",
  },
  {
    id: 64,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 4 videos id 64",
    authors: [],
    description: "",
  },
]);

// id_module 5
videos.set(5, [
  {
    id: 66,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Active,
    title: "video title module 5 videos id 66",
    authors: [],
    description: "",
  },
  {
    id: 67,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 5 videos id 67",
    authors: [],
    description: "",
  },
  {
    id: 68,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 5 videos id 68",
    authors: [],
    description: "",
  },
  {
    id: 69,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 5 videos id 69",
    authors: [],
    description: "",
  },
  {
    id: 70,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 5 videos id 70",
    authors: [],
    description: "",
  },
]);

// id_module 6
videos.set(6, [
  {
    id: 72,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 6 videos id 72",
    authors: [],
    description: "",
  },
  {
    id: 73,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 6 videos id 73",
    authors: [],
    description: "",
  },
  {
    id: 74,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 6 videos id 74",
    authors: [],
    description: "",
  },
  {
    id: 75,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Active,
    title: "video title module 6 videos id 75",
    authors: [],
    description: "",
  },
  {
    id: 76,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 6 videos id 76",
    authors: [],
    description: "",
  },
  {
    id: 77,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 6 videos id 77",
    authors: [],
    description: "",
  },
  {
    id: 78,
    type: EEntityType.Videos,
    src: "https://vjs.zencdn.net/v/oceans.mp4",
    poster: "https://vjs.zencdn.net/v/oceans.png",
    videoType: "",
    state: EEntityState.Default,
    title: "video title module 6 videos id 78",
    authors: [],
    description: "",
  },
]);

/**
 * TESTS
 */
const tests: TElemsList<number, ITest> | undefined = new Map();
// id_module 1
tests.set(1, [
  {
    id: 7,
    type: EEntityType.Tests,
    title: "Заголовок первого теста id 7",
    description: "Описание первого теста",
    state: EEntityState.Active,
  },
  {
    id: 14,
    type: EEntityType.Tests,
    title: "Заголовок второго теста id 14",
    description: "Описание второго теста",
    state: EEntityState.Default,
  },
  {
    id: 28,
    type: EEntityType.Tests,
    title: "Заголовок третьего теста id 28",
    description: "Описание третьего теста",
    state: EEntityState.Default,
  },
]);
// id_module 2
tests.set(2, [
  {
    id: 39,
    type: EEntityType.Tests,
    title: "Заголовок четвёртого теста id 39",
    description: "Описание четвёртого теста",
    state: EEntityState.Active,
  },
]);

/**
 * TESTS CONTENT
 */
const testsContent: TElemsList<number, ITestContent> | undefined = new Map();
// id_test 7
testsContent.set(7, [
  {
    id: 1,
    category: "Общие знания",
    type: "multiple",
    difficulty: "medium",
    slideNumber: 1,
    question: "Год основания федеральной налоговой службы?",
    state: EEntityState.Active,
    idAnswerCorrect: 1,
    answers: [
      { idAnswer: 1, answer: "2004", state: EEntityState.Unlocked },
      { idAnswer: 2, answer: "1998", state: EEntityState.Unlocked },
      { idAnswer: 3, answer: "2000", state: EEntityState.Unlocked },
      { idAnswer: 4, answer: "2002", state: EEntityState.Unlocked },
    ],
    guessed: EGuessed.Active,
  },
  {
    id: 2,
    category: "Общие знания",
    type: "multiple",
    difficulty: "easy",
    slideNumber: 2,
    question: "Какой режим налогообложения НЕ существует?",
    state: EEntityState.Default,
    idAnswerCorrect: 5,
    answers: [
      {
        idAnswer: 5,
        answer: "налог на оборот",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 6,
        answer: "основная система налогообложения",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 7,
        answer: "упрощенная система налогообложения",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 8,
        answer: " единый сельскохозяйственный налог",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 9,
        answer: "патентная система налогообложения",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 10,
        answer: "налог на профессиональный доход",
        state: EEntityState.Unlocked,
      },
    ],
    guessed: EGuessed.Undefined,
  },
  {
    id: 3,
    category: "Общие знания",
    type: "multiple",
    difficulty: "medium",
    slideNumber: 3,
    question:
      "В упрощённой системе налогообложения для юридических лиц налоговая ставка в процентах?",
    state: EEntityState.Default,
    idAnswerCorrect: 11,
    answers: [
      { idAnswer: 11, answer: "6%", state: EEntityState.Unlocked },
      { idAnswer: 12, answer: "8%", state: EEntityState.Unlocked },
      { idAnswer: 13, answer: "4%", state: EEntityState.Unlocked },
      { idAnswer: 14, answer: "10%", state: EEntityState.Unlocked },
    ],
    guessed: EGuessed.Undefined,
  },
  {
    id: 4,
    category: "Общие знания",
    type: "multiple",
    difficulty: "medium",
    slideNumber: 4,
    question:
      "Для какой категории граждан введён налог на профессиональный доход ",
    state: EEntityState.Default,
    idAnswerCorrect: 17,
    answers: [
      {
        idAnswer: 15,
        answer: "наёмных работников",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 16,
        answer: "сезонных работников",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 17,
        answer: "самозанятых",
        state: EEntityState.Unlocked,
      },
    ],
    guessed: EGuessed.Undefined,
  },
  /*{
    id: 5,
    category: "Общие знания",
    type: "boolean",
    difficulty: "easy",
    slideNumber: 5,
    question: "Срок уплаты транспортного налога физическим лицом",
    state: EEntityState.Default,
    idAnswerCorrect: 21,
    answers: [
      {
        idAnswer: 18,
        answer: "не позднее 1 октября",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 19,
        answer: "не позднее 1 ноября",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 20,
        answer: "не позднее 1 января",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 21,
        answer: "не позднее 1 декабря",
        state: EEntityState.Unlocked,
      },
    ],
    guessed: EGuessed.Undefined,
  },
  {
    id: 6,
    category: "Общие знания",
    type: "multiple",
    difficulty: "hard",
    slideNumber: 6,
    question:
      "Может ли иное лицо осуществить уплату государственной пошлины за плательщика?",
    state: EEntityState.Default,
    idAnswerCorrect: 23,
    answers: [
      { idAnswer: 22, answer: "Нет", state: EEntityState.Unlocked },
      { idAnswer: 23, answer: "Да", state: EEntityState.Unlocked },
    ],
    guessed: EGuessed.Undefined,
  },
  {
    id: 7,
    category: "Общие знания",
    type: "multiple",
    difficulty: "easy",
    slideNumber: 7,
    question:
      "С какого момента и до какого момента применяется налоговый вычет для соглашения о защите и поощрении капиталовложений (СЗПК)?",
    state: EEntityState.Default,
    idAnswerCorrect: 26,
    answers: [
      {
        idAnswer: 24,
        answer:
          "Начиная с налогового периода, следующего за полугодом представления уведомления о налоговом вычете для СЗПК",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 25,
        answer:
          "Начиная с налогового периода, следующего за месяцем представления уведомления о налоговом вычете для СЗПК",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 26,
        answer:
          "Начиная с налогового периода, следующего за годом представления уведомления о налоговом вычете для СЗПК",
        state: EEntityState.Unlocked,
      },
    ],
    guessed: EGuessed.Undefined,
  },
  {
    id: 8,
    category: "Общие знания",
    type: "multiple",
    difficulty: "medium",
    slideNumber: 8,
    question:
      "Размер страховых взносов для общества с ограниченной ответственностью?",
    state: EEntityState.Default,
    idAnswerCorrect: 29,
    answers: [
      {
        idAnswer: 27,
        answer:
          "На пенсионное страхование - 27%, на медицинское страхование - 9.1%, на социальное страхование - 0,9%, взносы за травматизм - от 0.2, до 8.5%",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 28,
        answer:
          "На пенсионное страхование - 20%, на медицинское страхование - 5.1%, на социальное страхование - 2,9%, взносы за травматизм - от 2.2, до 5.5%",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 29,
        answer:
          "На пенсионное страхование - 22%, на медицинское страхование - 5.1%, на социальное страхование - 2,9%, взносы за травматизм - от 0.2, до 8.5%",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 30,
        answer:
          "На пенсионное страхование - 18%, на медицинское страхование - 7%, на социальное страхование - 2,3%, взносы за травматизм - от 0.2, до 8.5%",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 31,
        answer:
          "На пенсионное страхование - 17%, на медицинское страхование - 3.1%, на социальное страхование - 1,9%, взносы за травматизм - от 2.7, до 6.5%",
        state: EEntityState.Unlocked,
      },
    ],
    guessed: EGuessed.Undefined,
  },
  {
    id: 9,
    category: "Общие знания",
    type: "multiple",
    difficulty: "hard",
    slideNumber: 9,
    question:
      "Может ли физическое лицо, не являющееся индивидуальным предпринимателем, являться налогоплательщиком НДС?",
    state: EEntityState.Default,
    idAnswerCorrect: 33,
    answers: [
      { idAnswer: 32, answer: "Да", state: EEntityState.Unlocked },
      { idAnswer: 33, answer: "Нет", state: EEntityState.Unlocked },
    ],
    guessed: EGuessed.Undefined,
  },
  {
    id: 10,
    category: "Общие знания",
    type: "boolean",
    difficulty: "medium",
    slideNumber: 10,
    question:
      "Какие страховые взносы Не платит индивидуальный предприниматель?",
    state: EEntityState.Default,
    idAnswerCorrect: 36,
    answers: [
      {
        idAnswer: 34,
        answer: "В пенсионный фонд",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 35,
        answer: "В фонд обязательного медицинского страхования",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 36,
        answer: "В фонд добровольного медицинского страхования",
        state: EEntityState.Unlocked,
      },
    ],
    guessed: EGuessed.Undefined,
  },*/
]);
// id_test 14
testsContent.set(14, [
  {
    id: 11,
    category: "Общие знания",
    type: "multiple",
    difficulty: "medium",
    slideNumber: 1,
    question: "Сколько будет 2 + 2?",
    state: EEntityState.Default,
    idAnswerCorrect: 37,
    answers: [
      { idAnswer: 37, answer: "4", state: EEntityState.Unlocked },
      { idAnswer: 38, answer: "5", state: EEntityState.Unlocked },
      { idAnswer: 39, answer: "6", state: EEntityState.Unlocked },
      { idAnswer: 40, answer: "7", state: EEntityState.Unlocked },
      { idAnswer: 41, answer: "8", state: EEntityState.Unlocked },
      { idAnswer: 42, answer: "9", state: EEntityState.Unlocked },
      { idAnswer: 43, answer: "10", state: EEntityState.Unlocked },
      { idAnswer: 44, answer: "11", state: EEntityState.Unlocked },
      { idAnswer: 45, answer: "12", state: EEntityState.Unlocked },
    ],
    guessed: EGuessed.Active,
  },
  {
    id: 12,
    category: "Общие знания",
    type: "multiple",
    difficulty: "easy",
    slideNumber: 2,
    question: "Столица Никарагуа?",
    state: EEntityState.Default,
    idAnswerCorrect: 48,
    answers: [
      {
        idAnswer: 46,
        answer: "Лиссабон",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 47,
        answer: "Рейкьявик",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 48,
        answer: "Манагуа",
        state: EEntityState.Unlocked,
      },
    ],
    guessed: EGuessed.Undefined,
  },
]);
// id_test 28
testsContent.set(28, [
  {
    id: 13,
    category: "Общие знания",
    type: "multiple",
    difficulty: "medium",
    slideNumber: 1,
    question: "Сейчас зима?",
    state: EEntityState.Default,
    idAnswerCorrect: 49,
    answers: [
      { idAnswer: 49, answer: "Да", state: EEntityState.Unlocked },
      { idAnswer: 50, answer: "Нет", state: EEntityState.Unlocked },
    ],
    guessed: EGuessed.Active,
  },
  {
    id: 14,
    category: "Общие знания",
    type: "multiple",
    difficulty: "easy",
    slideNumber: 2,
    question: "Из песни слов не ...?",
    state: EEntityState.Default,
    idAnswerCorrect: 53,
    answers: [
      {
        idAnswer: 51,
        answer: "убавишь",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 52,
        answer: "добавишь",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 53,
        answer: "выкинешь",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 54,
        answer: "с глаголом пишется раздельно",
        state: EEntityState.Unlocked,
      },
    ],
    guessed: EGuessed.Undefined,
  },
]);
// id_test 39
testsContent.set(39, [
  {
    id: 15,
    category: "Общие знания",
    type: "multiple",
    difficulty: "medium",
    slideNumber: 1,
    question: "Что такое Эдельвейс?",
    state: EEntityState.Default,
    idAnswerCorrect: 55,
    answers: [
      {
        idAnswer: 55,
        answer: "Горное травянистое растение семейства Сложноцветных",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 56,
        answer: "Полевое травянистое растение семейства Одноцветных",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 57,
        answer: "Луговое травянистое растение семейства Пучковых",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 58,
        answer: "Песчаное травянистое растение семейства Ложноцветных",
        state: EEntityState.Unlocked,
      },
    ],
    guessed: EGuessed.Active,
  },
  {
    id: 16,
    category: "Общие знания",
    type: "multiple",
    difficulty: "easy",
    slideNumber: 2,
    question: "Какого населённого пункта не существует?",
    state: EEntityState.Default,
    idAnswerCorrect: 61,
    answers: [
      {
        idAnswer: 59,
        answer: "Пыть-Ях",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 60,
        answer: "Куть-Ях",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 61,
        answer: "Гыть-Ях",
        state: EEntityState.Unlocked,
      },
    ],
    guessed: EGuessed.Undefined,
  },
]);

/**
 * ENTRANCE TESTS
 */
const entranceTests: IEntranceTest[] | undefined = [];
entranceTests.push(
  {
    id: 1,
    type: EEntityType.EntranceTests,
    title: "Готов ли ты к предпринимательству?",
    description: "Описание входного тестирования",
    state: EEntityState.Active,
  },
  {
    id: 2,
    type: EEntityType.EntranceTests,
    title: "Модуль входного тестирования 2",
    description: "Описание входного тестирования",
    state: EEntityState.Default,
  }
);

/**
 * ENTRANCE TESTS CONTENT
 */
const entranceTestsContent:
  | TElemsList<number, IEntranceTestContent>
  | undefined = new Map();
// id_entrance_test 1
entranceTestsContent.set(1, [
  {
    id: 1,
    category: "Общие знания",
    type: "multiple",
    difficulty: "medium",
    slideNumber: 1,
    question: "Entrance Test Год основания федеральной налоговой службы?",
    state: EEntityState.Active,
    idAnswerCorrect: 1,
    idAnswerUserSelected: [],
    answers: [
      { idAnswer: 1, answer: "2004", state: EEntityState.Unlocked },
      { idAnswer: 2, answer: "1998", state: EEntityState.Unlocked },
      { idAnswer: 3, answer: "2000", state: EEntityState.Unlocked },
      { idAnswer: 4, answer: "2002", state: EEntityState.Unlocked },
    ],
    guessed: EGuessed.Active,
  },
  {
    id: 2,
    category: "Общие знания",
    type: "multiple",
    difficulty: "easy",
    slideNumber: 2,
    question: "Entrance Test Какой режим налогообложения НЕ существует?",
    state: EEntityState.Default,
    idAnswerCorrect: 5,
    idAnswerUserSelected: [],
    answers: [
      {
        idAnswer: 5,
        answer: "налог на оборот",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 6,
        answer: "основная система налогообложения",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 7,
        answer: "упрощенная система налогообложения",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 8,
        answer: " единый сельскохозяйственный налог",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 9,
        answer: "патентная система налогообложения",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 10,
        answer: "налог на профессиональный доход",
        state: EEntityState.Unlocked,
      },
    ],
    guessed: EGuessed.Undefined,
  },
  {
    id: 3,
    category: "Общие знания",
    type: "multiple",
    difficulty: "medium",
    slideNumber: 3,
    question:
      "Entrance Test В упрощённой системе налогообложения для юридических лиц налоговая ставка в процентах?",
    state: EEntityState.Default,
    idAnswerCorrect: 11,
    idAnswerUserSelected: [],
    answers: [
      { idAnswer: 11, answer: "6%", state: EEntityState.Unlocked },
      { idAnswer: 12, answer: "8%", state: EEntityState.Unlocked },
      { idAnswer: 13, answer: "4%", state: EEntityState.Unlocked },
      { idAnswer: 14, answer: "10%", state: EEntityState.Unlocked },
    ],
    guessed: EGuessed.Undefined,
  },
  {
    id: 4,
    category: "Общие знания",
    type: "multiple",
    difficulty: "medium",
    slideNumber: 4,
    question:
      "Entrance Test Для какой категории граждан введён налог на профессиональный доход ",
    state: EEntityState.Default,
    idAnswerCorrect: 17,
    idAnswerUserSelected: [],
    answers: [
      {
        idAnswer: 15,
        answer: "наёмных работников",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 16,
        answer: "сезонных работников",
        state: EEntityState.Unlocked,
      },
      {
        idAnswer: 17,
        answer: "самозанятых",
        state: EEntityState.Unlocked,
      },
    ],
    guessed: EGuessed.Undefined,
  },
]);

export {
  modules,
  themes,
  videos,
  tests,
  testsContent,
  entranceTests,
  entranceTestsContent,
};
