import { EEntityState, EEntityType } from "@/types/enums";
import type { IEduCommonElement, ITest } from "@/types/interfaces";
import type { TElemsList } from "@/types/types";

class Tests implements IEduCommonElement {
  list: TElemsList<number, ITest> | undefined;

  public createList() {
    if (this.list === undefined) {
      this.list = new Map();
    }
    return this.list;
  }
  public addToList(): void {
    if (this.list instanceof Map && this.list.size === 0) {
      this.list.set(1, [
        {
          id: 1,
          type: EEntityType.Videos,
          src: "https://vk.com/video-30836025_456239619",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "module 1",
        },
        {
          id: 2,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 3,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 4,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 5,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 6,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 7,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 8,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 9,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 10,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 11,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 12,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 13,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 14,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 15,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 16,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 17,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 18,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 19,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 20,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 21,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 22,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 23,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 24,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 25,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 26,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 27,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
      ]);

      this.list.set(2, [
        {
          id: 1,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "module 2",
        },
        {
          id: 2,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
        {
          id: 3,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
        {
          id: 4,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
        {
          id: 5,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
        {
          id: 6,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
        {
          id: 7,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
        {
          id: 8,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
        {
          id: 9,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
        {
          id: 10,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
      ]);

      this.list.set(3, [
        {
          id: 1,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "module 3 theme 1",
        },
        {
          id: 2,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3 theme 2",
        },
        {
          id: 3,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3 theme 3",
        },
        {
          id: 4,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3",
        },
        {
          id: 5,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3",
        },
        {
          id: 6,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3",
        },
        {
          id: 7,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3",
        },
        {
          id: 8,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3",
        },
        {
          id: 9,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3",
        },
        {
          id: 10,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3",
        },
      ]);

      this.list.set(4, [
        {
          id: 1,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 2,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "module 4",
        },
        {
          id: 3,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 4,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 5,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 6,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 7,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 8,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 9,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 10,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 11,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 12,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 13,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 14,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
      ]);

      this.list.set(5, [
        {
          id: 1,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "module 5",
        },
        {
          id: 2,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 5",
        },
        {
          id: 3,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 5",
        },
        {
          id: 4,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 5",
        },
        {
          id: 5,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 5",
        },
      ]);

      this.list.set(6, [
        {
          id: 1,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 6",
        },
        {
          id: 2,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 6",
        },
        {
          id: 3,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 6",
        },
        {
          id: 4,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "module 6",
        },
        {
          id: 5,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 6",
        },
        {
          id: 6,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 6",
        },
        {
          id: 7,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 6",
        },
      ]);
    }
  }
  public getList() {
    return this.list;
  }
}

export { Videos };
