import { EEntityState, EEntityType } from "@/types/enums";
import type { IEduCommonElement, IVideo } from "@/types/interfaces";
import type { TElemsList } from "@/types/types";

class Videos implements IEduCommonElement {
  list: TElemsList<number, IVideo> | undefined;

  public createList() {
    if (this.list === undefined) {
      this.list = new Map();
    }
    return this.list;
  }
  public addToList(): void {
    if (this.list instanceof Map && this.list.size === 0) {
      // module 1
      this.list.set(1, [
        {
          id: 1,
          type: EEntityType.Videos,
          src: "https://vk.com/video-30836025_456239619",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "video title module 1 videos id 1",
        },
        {
          id: 2,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 2",
        },
        {
          id: 3,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 3",
        },
        {
          id: 4,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 4",
        },
        {
          id: 5,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 5",
        },
        {
          id: 6,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 6",
        },
        {
          id: 8,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 8",
        },
        {
          id: 9,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 9",
        },
        {
          id: 10,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 10",
        },
        {
          id: 11,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 11",
        },
        {
          id: 12,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 12",
        },
        {
          id: 13,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 13",
        },
        {
          id: 15,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 15",
        },
        {
          id: 16,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 16",
        },
        {
          id: 17,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 17",
        },
        {
          id: 18,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 18",
        },
        {
          id: 19,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 19",
        },
        {
          id: 20,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 20",
        },
        {
          id: 21,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 21",
        },
        {
          id: 22,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 22",
        },
        {
          id: 23,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 23",
        },
        {
          id: 24,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 24",
        },
        {
          id: 25,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 25",
        },
        {
          id: 26,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 26",
        },
        {
          id: 27,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 1 videos id 27",
        },
      ]);

      // module 2
      this.list.set(2, [
        {
          id: 29,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "video title module 2 videos id 29",
        },
        {
          id: 30,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 2 videos id 30",
        },
        {
          id: 31,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 2 videos id 31",
        },
        {
          id: 32,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 2 videos id 32",
        },
        {
          id: 33,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 2 videos id 33",
        },
        {
          id: 34,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 2 videos id 34",
        },
        {
          id: 35,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 2 videos id 35",
        },
        {
          id: 36,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 2 videos id 36",
        },
        {
          id: 37,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 2 videos id 37",
        },
        {
          id: 38,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 2 videos id 38",
        },
      ]);

      // module 3
      this.list.set(3, [
        {
          id: 40,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "video title module 3 videos theme 1 id 40",
        },
        {
          id: 41,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 3 videos theme 2 id 41",
        },
        {
          id: 42,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 3 videos theme 3 id 42",
        },
        {
          id: 43,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 3 videos id 43",
        },
        {
          id: 44,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 3 videos id 44",
        },
        {
          id: 45,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 3 videos id 45",
        },
        {
          id: 46,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 3 videos id 46",
        },
        {
          id: 47,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 3 videos id 47",
        },
        {
          id: 48,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 3 videos id 48",
        },
        {
          id: 49,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 3 videos id 49",
        },
      ]);

      // module 4
      this.list.set(4, [
        {
          id: 51,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 4 videos id 51",
        },
        {
          id: 52,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "video title module 4 videos id 52",
        },
        {
          id: 53,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 4 videos id 53",
        },
        {
          id: 54,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 4 videos id 54",
        },
        {
          id: 55,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 4 videos id 55",
        },
        {
          id: 56,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 4 videos id 56",
        },
        {
          id: 57,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 4 videos id 57",
        },
        {
          id: 58,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 4 videos id 58",
        },
        {
          id: 59,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 4 videos id 59",
        },
        {
          id: 60,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 4 videos id 60",
        },
        {
          id: 61,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 4 videos id 61",
        },
        {
          id: 62,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 4 videos id 62",
        },
        {
          id: 63,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 4 videos id 63",
        },
        {
          id: 64,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 4 videos id 64",
        },
      ]);

      // module 5
      this.list.set(5, [
        {
          id: 66,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "video title module 5 videos id 66",
        },
        {
          id: 67,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 5 videos id 67",
        },
        {
          id: 68,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 5 videos id 68",
        },
        {
          id: 69,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 5 videos id 69",
        },
        {
          id: 70,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 5 videos id 70",
        },
      ]);

      // module 6
      this.list.set(6, [
        {
          id: 72,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 6 videos id 72",
        },
        {
          id: 73,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 6 videos id 73",
        },
        {
          id: 74,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 6 videos id 74",
        },
        {
          id: 75,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "video title module 6 videos id 75",
        },
        {
          id: 76,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 6 videos id 76",
        },
        {
          id: 77,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 6 videos id 77",
        },
        {
          id: 78,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "video title module 6 videos id 78",
        },
      ]);
    }
  }
  public getList() {
    return this.list;
  }
}

export { Videos };
