import { EEntityState, EEntityType } from "@/types/enums";
import type { IEduCommonElement, IVideo } from "@/types/interfaces";
import type { TElemsList } from "@/types/types";

class Videos implements IEduCommonElement {
  list: TElemsList<number, IVideo> | undefined;

  public createList() {
    if (this.list === undefined) {
      this.list = new Map();
    }
    return this.list;
  }
  public addToList(): void {
    if (this.list instanceof Map && this.list.size === 0) {
      this.list.set(1, [
        {
          id: 1,
          type: EEntityType.Videos,
          src: "https://vk.com/video-30836025_456239619",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "module 1",
        },
        {
          id: 2,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 3,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 4,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 5,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 6,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 7,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 8,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 9,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 10,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 11,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 12,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 13,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 14,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 15,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 16,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 17,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 18,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 19,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 20,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 21,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 22,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 23,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 24,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 25,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 26,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
        {
          id: 27,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 1",
        },
      ]);

      this.list.set(2, [
        {
          id: 28,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "module 2",
        },
        {
          id: 29,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
        {
          id: 30,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
        {
          id: 31,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
        {
          id: 32,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
        {
          id: 33,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
        {
          id: 34,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
        {
          id: 35,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
        {
          id: 36,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
        {
          id: 37,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 2",
        },
      ]);

      this.list.set(3, [
        {
          id: 38,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "module 3 theme 1",
        },
        {
          id: 39,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3 theme 2",
        },
        {
          id: 40,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3 theme 3",
        },
        {
          id: 41,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3",
        },
        {
          id: 42,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3",
        },
        {
          id: 43,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3",
        },
        {
          id: 44,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3",
        },
        {
          id: 45,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3",
        },
        {
          id: 46,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3",
        },
        {
          id: 47,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 3",
        },
      ]);

      this.list.set(4, [
        {
          id: 48,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 49,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "module 4",
        },
        {
          id: 50,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 51,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 52,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 53,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 54,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 55,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 56,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 57,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 58,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 59,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 60,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
        {
          id: 61,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 4",
        },
      ]);

      this.list.set(5, [
        {
          id: 62,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "module 5",
        },
        {
          id: 63,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 5",
        },
        {
          id: 64,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 5",
        },
        {
          id: 65,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 5",
        },
        {
          id: 66,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 5",
        },
      ]);

      this.list.set(6, [
        {
          id: 67,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 6",
        },
        {
          id: 68,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 6",
        },
        {
          id: 69,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 6",
        },
        {
          id: 70,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Active,
          title: "module 6",
        },
        {
          id: 71,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 6",
        },
        {
          id: 72,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 6",
        },
        {
          id: 73,
          type: EEntityType.Videos,
          src: "https://www.youtube.com/watch?v=0ysi6DkeGmc",
          videoType: 'video/ogg; codecs="theora, vorbis"',
          state: EEntityState.Default,
          title: "module 6",
        },
      ]);
    }
  }
  public getList() {
    return this.list;
  }
}

export { Videos };
